// Package payloads provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package payloads

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApprovalAttestationV1Version.
const (
	ApprovalAttestationv1 ApprovalAttestationV1Version = "approval-attestation/v1"
)

// Valid indicates whether the value is a known member of the ApprovalAttestationV1Version enum.
func (e ApprovalAttestationV1Version) Valid() bool {
	switch e {
	case ApprovalAttestationv1:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalAttestedKeyProofVersion.
const (
	ApprovalAttestedKeyProofv1 ApprovalAttestedKeyProofVersion = "approval-attested-key-proof/v1"
)

// Valid indicates whether the value is a known member of the ApprovalAttestedKeyProofVersion enum.
func (e ApprovalAttestedKeyProofVersion) Valid() bool {
	switch e {
	case ApprovalAttestedKeyProofv1:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalChallengeVersion.
const (
	ApprovalChallengev1 ApprovalChallengeVersion = "approval-challenge/v1"
)

// Valid indicates whether the value is a known member of the ApprovalChallengeVersion enum.
func (e ApprovalChallengeVersion) Valid() bool {
	switch e {
	case ApprovalChallengev1:
		return true
	default:
		return false
	}
}

// Defines values for AttestationSecurityType.
const (
	AndroidStrongbox AttestationSecurityType = "android_strongbox"
	AndroidTee       AttestationSecurityType = "android_tee"
	IosSecureEnclave AttestationSecurityType = "ios_secure_enclave"
	PlayIntegrity    AttestationSecurityType = "play_integrity"
	Software         AttestationSecurityType = "software"
)

// Valid indicates whether the value is a known member of the AttestationSecurityType enum.
func (e AttestationSecurityType) Valid() bool {
	switch e {
	case AndroidStrongbox:
		return true
	case AndroidTee:
		return true
	case IosSecureEnclave:
		return true
	case PlayIntegrity:
		return true
	case Software:
		return true
	default:
		return false
	}
}

// Defines values for KeyPurpose.
const (
	Age KeyPurpose = "age"
	Gpg KeyPurpose = "gpg"
	Ssh KeyPurpose = "ssh"
)

// Valid indicates whether the value is a known member of the KeyPurpose enum.
func (e KeyPurpose) Valid() bool {
	switch e {
	case Age:
		return true
	case Gpg:
		return true
	case Ssh:
		return true
	default:
		return false
	}
}

// Defines values for MailboxBrowserApprovalBindingFormat.
const (
	BrowserApprovalDecisionBindingv1Json MailboxBrowserApprovalBindingFormat = "browser-approval-decision-binding/v1+json"
)

// Valid indicates whether the value is a known member of the MailboxBrowserApprovalBindingFormat enum.
func (e MailboxBrowserApprovalBindingFormat) Valid() bool {
	switch e {
	case BrowserApprovalDecisionBindingv1Json:
		return true
	default:
		return false
	}
}

// Defines values for MailboxBrowserApprovalDecision.
const (
	MailboxBrowserApprovalDecisionApproved MailboxBrowserApprovalDecision = "approved"
	MailboxBrowserApprovalDecisionDenied   MailboxBrowserApprovalDecision = "denied"
)

// Valid indicates whether the value is a known member of the MailboxBrowserApprovalDecision enum.
func (e MailboxBrowserApprovalDecision) Valid() bool {
	switch e {
	case MailboxBrowserApprovalDecisionApproved:
		return true
	case MailboxBrowserApprovalDecisionDenied:
		return true
	default:
		return false
	}
}

// Defines values for MailboxBrowserApprovalDecisionBindingV1RequestEnvelopeType.
const (
	MailboxBrowserApprovalDecisionBindingV1RequestEnvelopeTypeBrowserApprovalRequest MailboxBrowserApprovalDecisionBindingV1RequestEnvelopeType = "browser_approval_request"
)

// Valid indicates whether the value is a known member of the MailboxBrowserApprovalDecisionBindingV1RequestEnvelopeType enum.
func (e MailboxBrowserApprovalDecisionBindingV1RequestEnvelopeType) Valid() bool {
	switch e {
	case MailboxBrowserApprovalDecisionBindingV1RequestEnvelopeTypeBrowserApprovalRequest:
		return true
	default:
		return false
	}
}

// Defines values for MailboxBrowserApprovalDecisionBindingV1Version.
const (
	BrowserApprovalDecisionBindingv1 MailboxBrowserApprovalDecisionBindingV1Version = "browser-approval-decision-binding/v1"
)

// Valid indicates whether the value is a known member of the MailboxBrowserApprovalDecisionBindingV1Version enum.
func (e MailboxBrowserApprovalDecisionBindingV1Version) Valid() bool {
	switch e {
	case BrowserApprovalDecisionBindingv1:
		return true
	default:
		return false
	}
}

// Defines values for MailboxBrowserApprovalResponseStatus.
const (
	Decided MailboxBrowserApprovalResponseStatus = "decided"
)

// Valid indicates whether the value is a known member of the MailboxBrowserApprovalResponseStatus enum.
func (e MailboxBrowserApprovalResponseStatus) Valid() bool {
	switch e {
	case Decided:
		return true
	default:
		return false
	}
}

// Defines values for MailboxEnrollResponseApprovedV1Status.
const (
	MailboxEnrollResponseApprovedV1StatusApproved MailboxEnrollResponseApprovedV1Status = "approved"
)

// Valid indicates whether the value is a known member of the MailboxEnrollResponseApprovedV1Status enum.
func (e MailboxEnrollResponseApprovedV1Status) Valid() bool {
	switch e {
	case MailboxEnrollResponseApprovedV1StatusApproved:
		return true
	default:
		return false
	}
}

// Defines values for MailboxEnrollResponseRejectedV1Status.
const (
	Rejected MailboxEnrollResponseRejectedV1Status = "rejected"
)

// Valid indicates whether the value is a known member of the MailboxEnrollResponseRejectedV1Status enum.
func (e MailboxEnrollResponseRejectedV1Status) Valid() bool {
	switch e {
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for MailboxEnvelopeType.
const (
	MailboxEnvelopeTypeAgeUnwrap               MailboxEnvelopeType = "age_unwrap"
	MailboxEnvelopeTypeBrowserApprovalRequest  MailboxEnvelopeType = "browser_approval_request"
	MailboxEnvelopeTypeBrowserApprovalResponse MailboxEnvelopeType = "browser_approval_response"
	MailboxEnvelopeTypeCaptchaRequest          MailboxEnvelopeType = "captcha_request"
	MailboxEnvelopeTypeCaptchaResponse         MailboxEnvelopeType = "captcha_response"
	MailboxEnvelopeTypeEnroll                  MailboxEnvelopeType = "enroll"
	MailboxEnvelopeTypeGpgDecrypt              MailboxEnvelopeType = "gpg_decrypt"
	MailboxEnvelopeTypeGpgSign                 MailboxEnvelopeType = "gpg_sign"
	MailboxEnvelopeTypeLinkApproval            MailboxEnvelopeType = "link_approval"
	MailboxEnvelopeTypeLinkRejection           MailboxEnvelopeType = "link_rejection"
	MailboxEnvelopeTypeLinkRequest             MailboxEnvelopeType = "link_request"
	MailboxEnvelopeTypePkcs11Derive            MailboxEnvelopeType = "pkcs11_derive"
	MailboxEnvelopeTypePkcs11Sign              MailboxEnvelopeType = "pkcs11_sign"
	MailboxEnvelopeTypeSshAuth                 MailboxEnvelopeType = "ssh_auth"
	MailboxEnvelopeTypeSshSign                 MailboxEnvelopeType = "ssh_sign"
)

// Valid indicates whether the value is a known member of the MailboxEnvelopeType enum.
func (e MailboxEnvelopeType) Valid() bool {
	switch e {
	case MailboxEnvelopeTypeAgeUnwrap:
		return true
	case MailboxEnvelopeTypeBrowserApprovalRequest:
		return true
	case MailboxEnvelopeTypeBrowserApprovalResponse:
		return true
	case MailboxEnvelopeTypeCaptchaRequest:
		return true
	case MailboxEnvelopeTypeCaptchaResponse:
		return true
	case MailboxEnvelopeTypeEnroll:
		return true
	case MailboxEnvelopeTypeGpgDecrypt:
		return true
	case MailboxEnvelopeTypeGpgSign:
		return true
	case MailboxEnvelopeTypeLinkApproval:
		return true
	case MailboxEnvelopeTypeLinkRejection:
		return true
	case MailboxEnvelopeTypeLinkRequest:
		return true
	case MailboxEnvelopeTypePkcs11Derive:
		return true
	case MailboxEnvelopeTypePkcs11Sign:
		return true
	case MailboxEnvelopeTypeSshAuth:
		return true
	case MailboxEnvelopeTypeSshSign:
		return true
	default:
		return false
	}
}

// Defines values for MailboxEnvelopeV1V.
const (
	MailboxEnvelopeV1VN1 MailboxEnvelopeV1V = 1
)

// Valid indicates whether the value is a known member of the MailboxEnvelopeV1V enum.
func (e MailboxEnvelopeV1V) Valid() bool {
	switch e {
	case MailboxEnvelopeV1VN1:
		return true
	default:
		return false
	}
}

// Defines values for SigningErrorCode.
const (
	SigningErrorCodeN1 SigningErrorCode = 1
	SigningErrorCodeN2 SigningErrorCode = 2
	SigningErrorCodeN3 SigningErrorCode = 3
	SigningErrorCodeN4 SigningErrorCode = 4
	SigningErrorCodeN5 SigningErrorCode = 5
	SigningErrorCodeN6 SigningErrorCode = 6
)

// Valid indicates whether the value is a known member of the SigningErrorCode enum.
func (e SigningErrorCode) Valid() bool {
	switch e {
	case SigningErrorCodeN1:
		return true
	case SigningErrorCodeN2:
		return true
	case SigningErrorCodeN3:
		return true
	case SigningErrorCodeN4:
		return true
	case SigningErrorCodeN5:
		return true
	case SigningErrorCodeN6:
		return true
	default:
		return false
	}
}

// ApprovalAttestationV1 Service-issued approval attestation embedded into the Longfellow proof witness.
type ApprovalAttestationV1 struct {
	// Bytes RFC 4648 standard base64 with `=` padding for the `approval-attestation/v1` bytes embedded into the Longfellow proof witness.
	Bytes []byte `json:"bytes"`

	// Signature RFC 4648 standard base64 with `=` padding for the raw 64-byte P-256 `r || s` signature over `SHA256(bytes)`.
	Signature []byte `json:"signature"`

	// Version Canonical approval attestation format version.
	Version ApprovalAttestationV1Version `json:"version"`
}

// ApprovalAttestationV1Version Canonical approval attestation format version.
type ApprovalAttestationV1Version string

// ApprovalAttestedKeyProof Canonical Longfellow approval proof carried inside encrypted approval responses.
type ApprovalAttestedKeyProof struct {
	// Attestation Service-issued approval attestation embedded into the Longfellow proof witness.
	Attestation ApprovalAttestationV1 `json:"attestation"`

	// Challenge Canonical Longfellow / attested-key-zk approval challenge. Producer sends this inside the request payload; the approver binds it into the approval proof returned in the response payload.
	Challenge ApprovalChallenge `json:"challenge"`

	// Proof RFC 4648 standard base64 with `=` padding for the Longfellow approval proof bytes.
	Proof []byte `json:"proof"`

	// Statement Public Longfellow statement bound into the zero-knowledge proof.
	Statement ApprovalProofStatement `json:"statement"`

	// Version Canonical approval proof format version.
	Version ApprovalAttestedKeyProofVersion `json:"version"`
}

// ApprovalAttestedKeyProofVersion Canonical approval proof format version.
type ApprovalAttestedKeyProofVersion string

// ApprovalChallenge Canonical Longfellow / attested-key-zk approval challenge. Producer sends this inside the request payload; the approver binds it into the approval proof returned in the response payload.
type ApprovalChallenge struct {
	// Nonce Opaque nonce bound into the approval challenge and proof statement.
	Nonce string `json:"nonce"`

	// PlaintextHash SHA-256 digest of the approved plaintext, formatted as `sha256:<hex>`.
	PlaintextHash string `json:"plaintext_hash"`

	// RequestId Relay request id that scopes the approval proof.
	RequestId string `json:"request_id"`

	// Version Canonical approval challenge format version.
	Version ApprovalChallengeVersion `json:"version"`
}

// ApprovalChallengeVersion Canonical approval challenge format version.
type ApprovalChallengeVersion string

// ApprovalProofStatement Public Longfellow statement bound into the zero-knowledge proof.
type ApprovalProofStatement struct {
	// AppIdHashHex Lowercase hex-encoded SHA-256 hash of the mobile app identifier.
	AppIdHashHex string `json:"app_id_hash_hex"`

	// ApprovalHashHex Lowercase hex-encoded SHA-256 hash of the canonical approval challenge JSON.
	ApprovalHashHex string `json:"approval_hash_hex"`

	// AudienceHashHex Lowercase hex-encoded SHA-256 hash of the verifier audience string.
	AudienceHashHex string `json:"audience_hash_hex"`

	// ChallengeNonceHex Lowercase hex-encoded SHA-256 hash of `ApprovalChallenge.nonce`.
	ChallengeNonceHex string `json:"challenge_nonce_hex"`

	// IssuerPublicKeyHex Lowercase hex-encoded compressed P-256 issuer public key (66 hex chars, 33 bytes: `0x02`/`0x03` || X).
	IssuerPublicKeyHex string `json:"issuer_public_key_hex"`

	// Now Unix timestamp in seconds embedded into the approval proof statement.
	Now int64 `json:"now"`

	// PolicyVersion Policy version embedded into the approval proof statement.
	PolicyVersion int32 `json:"policy_version"`
}

// AttestationSecurityType Combined platform and security level for attestation.
type AttestationSecurityType string

// DisplayField A single label/value row rendered on the approval surface.
type DisplayField struct {
	// Expandable Field can be expanded to show additional content.
	Expandable *bool `json:"expandable,omitempty"`

	// Icon Optional SF Symbol or Material icon name.
	Icon *string `json:"icon,omitempty"`

	// Label Short label for the field.
	Label string `json:"label"`

	// Monospace Render the value in a monospace font.
	Monospace *bool `json:"monospace,omitempty"`

	// Multiline Render the value across multiple lines.
	Multiline *bool `json:"multiline,omitempty"`

	// Sensitive Value contains sensitive information; UI may mask it.
	Sensitive *bool `json:"sensitive,omitempty"`

	// Value Value to display.
	Value string `json:"value"`
}

// DisplaySchema Optional approval-UI metadata. Producers populate this on a best-effort basis; approvers MUST render the wire payload regardless of presence.
type DisplaySchema struct {
	Fields []DisplayField `json:"fields"`

	// HistoryTitle Shorter title for the history list view.
	HistoryTitle *string `json:"history_title,omitempty"`

	// Icon Optional icon name.
	Icon *string `json:"icon,omitempty"`

	// Subtitle Subtitle with additional context.
	Subtitle *string `json:"subtitle,omitempty"`

	// Title Main title for the approval screen.
	Title string `json:"title"`
}

// KeyMetadataAttestation Attestation proof that a key was created on attested device hardware.
type KeyMetadataAttestation struct {
	// Assertion RFC 4648 standard base64 with `=` padding for the App Attest assertion or software signature.
	Assertion []byte `json:"assertion"`

	// AttestationObject RFC 4648 standard base64 with `=` padding for the Apple CBOR attestation object used by hardware attestation.
	AttestationObject *[]byte `json:"attestation_object,omitempty"`

	// AttestationPublicKeyHex Lowercase hex-encoded attestation key public key (66 hex chars for P-256 33-byte compressed key).
	AttestationPublicKeyHex *string `json:"attestation_public_key_hex,omitempty"`

	// AttestationTimestamp Unix timestamp in milliseconds.
	AttestationTimestamp int64 `json:"attestation_timestamp"`

	// AttestationType Combined platform and security level for attestation.
	AttestationType AttestationSecurityType `json:"attestation_type"`

	// Challenge RFC 4648 standard base64 with `=` padding for `SHA256(id || public_key || created_at || device_auth_public_key)`.
	Challenge []byte `json:"challenge"`

	// PublicKeyHex Lowercase hex-encoded public key being attested (66 hex chars for P-256 33-byte compressed key, or 64 hex chars for Ed25519 32-byte key).
	PublicKeyHex string `json:"public_key_hex"`
}

// KeyPurpose Purpose of an enrolled key.
type KeyPurpose string

// MailboxAgeUnwrapRequestPayloadV1 Request payload for the `age_unwrap` envelope type. The approver unwraps an age `X25519` recipient stanza using the on-device X25519 key matching `recipient_public_hex`.
type MailboxAgeUnwrapRequestPayloadV1 struct {
	// ApprovalChallenge Canonical Longfellow / attested-key-zk approval challenge. Producer sends this inside the request payload; the approver binds it into the approval proof returned in the response payload.
	ApprovalChallenge *ApprovalChallenge `json:"approval_challenge,omitempty"`

	// Display Optional approval-UI metadata. Producers populate this on a best-effort basis; approvers MUST render the wire payload regardless of presence.
	Display *DisplaySchema `json:"display,omitempty"`

	// EphemeralPublicHex Lowercase hex-encoded sender's ephemeral X25519 public key (64 hex chars for the 32-byte key).
	EphemeralPublicHex string `json:"ephemeral_public_hex"`

	// RecipientPublicHex Lowercase hex-encoded recipient's X25519 public key (64 hex chars for the 32-byte key).
	RecipientPublicHex string `json:"recipient_public_hex"`

	// SourceInfo Optional context about the requesting system. Producers populate this on a best-effort basis; approvers MUST NOT make security decisions on unauthenticated source metadata.
	SourceInfo *SourceInfo `json:"source_info,omitempty"`

	// WrappedFileKey RFC 4648 standard base64 with `=` padding for the wrapped file key for decryption.
	WrappedFileKey []byte `json:"wrapped_file_key"`
}

// MailboxAgeUnwrapResponseFailureV1 Failure branch of `MailboxAgeUnwrapResponsePayloadV1`.
type MailboxAgeUnwrapResponseFailureV1 struct {
	// ErrorCode Numeric error code returned in `*ResponsePayloadV1.error_code` when an approval flow fails. `1=rejected`, `2=timeout`, `3=key_not_found`, `4=invalid_payload`, `5=attestation_failed`, `6=internal_error`.
	ErrorCode SigningErrorCode `json:"error_code"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"error_message,omitempty"`
}

// MailboxAgeUnwrapResponsePayloadV1 Response payload for the `age_unwrap` envelope type. Discriminated as a success / failure pair.
type MailboxAgeUnwrapResponsePayloadV1 struct {
	union json.RawMessage
}

// MailboxAgeUnwrapResponseSuccessV1 Success branch of `MailboxAgeUnwrapResponsePayloadV1`.
type MailboxAgeUnwrapResponseSuccessV1 struct {
	// ApprovalProof Canonical Longfellow approval proof carried inside encrypted approval responses.
	ApprovalProof *ApprovalAttestedKeyProof `json:"approval_proof,omitempty"`

	// FileKey RFC 4648 standard base64 with `=` padding for the unwrapped age file key.
	FileKey []byte `json:"file_key"`
}

// MailboxBrowserApprovalBindingFormat Canonical byte format signed by the mobile approval key.
type MailboxBrowserApprovalBindingFormat string

// MailboxBrowserApprovalDecision Mobile user's signed approval decision.
type MailboxBrowserApprovalDecision string

// MailboxBrowserApprovalDecisionBindingV1 Canonical JSON object whose UTF-8 bytes are signed by the mobile approval key. Producers encode these fields in lexicographic property order with no insignificant whitespace and place the resulting bytes in `MailboxBrowserApprovalResponsePayloadV1.approval_binding_bytes`.
type MailboxBrowserApprovalDecisionBindingV1 struct {
	// ApprovalId Approval id copied from the request payload.
	ApprovalId string `json:"approval_id"`

	// BrowserPublicKeyAlgorithm Browser public key algorithm copied from the request payload.
	BrowserPublicKeyAlgorithm string `json:"browser_public_key_algorithm"`

	// BrowserPublicKeyThumbprint Browser public key thumbprint copied from the request payload.
	BrowserPublicKeyThumbprint string `json:"browser_public_key_thumbprint"`

	// DecidedAt RFC 3339 UTC timestamp of the mobile decision.
	DecidedAt string `json:"decided_at"`

	// Decision Mobile user's signed approval decision.
	Decision MailboxBrowserApprovalDecision `json:"decision"`

	// ExpiresAt Request expiry copied from the request payload.
	ExpiresAt string `json:"expires_at"`

	// Nonce Nonce copied from the request payload.
	Nonce string `json:"nonce"`

	// PairingTranscriptHash SHA-256 hash of the service-mobile pairing transcript.
	PairingTranscriptHash string `json:"pairing_transcript_hash"`

	// RequestEnvelopeId Envelope id of the browser approval request being answered.
	RequestEnvelopeId openapi_types.UUID `json:"request_envelope_id"`

	// RequestEnvelopeIssuedAt Envelope `issued_at` timestamp of the request being answered.
	RequestEnvelopeIssuedAt string `json:"request_envelope_issued_at"`

	// RequestEnvelopeType Envelope type of the request being answered.
	RequestEnvelopeType MailboxBrowserApprovalDecisionBindingV1RequestEnvelopeType `json:"request_envelope_type"`

	// RequestedCapability Requested capability copied from the request payload.
	RequestedCapability string `json:"requested_capability"`

	// RequesterClientId Requester client id copied from the request payload.
	RequesterClientId string `json:"requester_client_id"`

	// RequesterOrigin Requester origin copied from the request payload.
	RequesterOrigin string `json:"requester_origin"`

	// ServiceMobilePairingId Stable id for the service-mobile E2EE mailbox pairing.
	ServiceMobilePairingId string `json:"service_mobile_pairing_id"`

	// Version Canonical decision binding schema version.
	Version MailboxBrowserApprovalDecisionBindingV1Version `json:"version"`
}

// MailboxBrowserApprovalDecisionBindingV1RequestEnvelopeType Envelope type of the request being answered.
type MailboxBrowserApprovalDecisionBindingV1RequestEnvelopeType string

// MailboxBrowserApprovalDecisionBindingV1Version Canonical decision binding schema version.
type MailboxBrowserApprovalDecisionBindingV1Version string

// MailboxBrowserApprovalRequestPayloadV1 Request payload for the `browser_approval_request` envelope type. A service requester sends this to the paired mobile device when a browser key needs approval for a generic capability.
type MailboxBrowserApprovalRequestPayloadV1 struct {
	// ApprovalId Opaque service-scoped approval id.
	ApprovalId string `json:"approval_id"`

	// BrowserDisplayName Human-readable browser/device label shown to the mobile user.
	BrowserDisplayName string `json:"browser_display_name"`

	// BrowserPlatform Best-effort browser platform hint shown to the mobile user.
	BrowserPlatform string `json:"browser_platform"`

	// BrowserPublicKeyAlgorithm Browser public key algorithm identifier, e.g. `ES256` or `Ed25519`.
	BrowserPublicKeyAlgorithm string `json:"browser_public_key_algorithm"`

	// BrowserPublicKeyThumbprint Thumbprint of the browser public key being approved. Producers SHOULD use `sha256:<base64url-no-padding>` for JWK thumbprints.
	BrowserPublicKeyThumbprint string `json:"browser_public_key_thumbprint"`

	// BrowserUserAgent Optional user-agent hint for display and diagnostics.
	BrowserUserAgent *string `json:"browser_user_agent,omitempty"`

	// ExpiresAt RFC 3339 UTC timestamp after which the request is invalid.
	ExpiresAt string `json:"expires_at"`

	// IssuedAt RFC 3339 UTC timestamp with canonical `Z` suffix.
	IssuedAt string `json:"issued_at"`

	// Nonce Opaque nonce bound into the mobile-signed decision.
	Nonce string `json:"nonce"`

	// RequestedCapability Generic capability requested by the service.
	RequestedCapability string `json:"requested_capability"`

	// RequesterClientId Service/requester client id that created the approval request.
	RequesterClientId string `json:"requester_client_id"`

	// RequesterDisplayName Human-readable requester name shown to the mobile user.
	RequesterDisplayName string `json:"requester_display_name"`

	// RequesterOrigin Origin of the requester that will receive/use the browser credential.
	RequesterOrigin string `json:"requester_origin"`
}

// MailboxBrowserApprovalResponsePayloadV1 Response payload for the `browser_approval_response` envelope type. The response carries the mobile decision plus the exact canonical bytes and signature over `MailboxBrowserApprovalDecisionBindingV1`.
type MailboxBrowserApprovalResponsePayloadV1 struct {
	// ApprovalBindingBytes RFC 4648 standard base64 with `=` padding for the canonical `MailboxBrowserApprovalDecisionBindingV1` UTF-8 JSON bytes.
	ApprovalBindingBytes []byte `json:"approval_binding_bytes"`

	// ApprovalBindingFormat Canonical byte format signed by the mobile approval key.
	ApprovalBindingFormat MailboxBrowserApprovalBindingFormat `json:"approval_binding_format"`

	// ApprovalId Approval id copied from the request payload.
	ApprovalId string `json:"approval_id"`

	// ApprovalSignature RFC 4648 standard base64 with `=` padding for the signature over `approval_binding_bytes`.
	ApprovalSignature []byte `json:"approval_signature"`

	// DecidedAt RFC 3339 UTC timestamp of the mobile decision.
	DecidedAt string `json:"decided_at"`

	// Decision Mobile user's signed approval decision.
	Decision MailboxBrowserApprovalDecision `json:"decision"`

	// RequestEnvelopeId Envelope id of the browser approval request being answered.
	RequestEnvelopeId openapi_types.UUID `json:"request_envelope_id"`

	// SigningKeyId Mobile signing key id that produced `approval_signature`.
	SigningKeyId string `json:"signing_key_id"`

	// Status Response lifecycle status. The signed `decision` carries the approval outcome.
	Status MailboxBrowserApprovalResponseStatus `json:"status"`
}

// MailboxBrowserApprovalResponseStatus Response lifecycle status. The signed `decision` carries the approval outcome.
type MailboxBrowserApprovalResponseStatus string

// MailboxEnrollRequestPayloadV1 Request payload for the `enroll` envelope type. The approver creates a new key for the requested `purpose` and returns its public material.
type MailboxEnrollRequestPayloadV1 struct {
	// Algorithm Key algorithm to use. Approver MUST reject unknown algorithms.
	Algorithm *string `json:"algorithm,omitempty"`

	// ApprovalChallenge Canonical Longfellow / attested-key-zk approval challenge. Producer sends this inside the request payload; the approver binds it into the approval proof returned in the response payload.
	ApprovalChallenge *ApprovalChallenge `json:"approval_challenge,omitempty"`

	// Display Optional approval-UI metadata. Producers populate this on a best-effort basis; approvers MUST render the wire payload regardless of presence.
	Display *DisplaySchema `json:"display,omitempty"`

	// IncludeCertification Include a self-certification signature for GPG export. Ignored for non-GPG purposes.
	IncludeCertification *bool `json:"include_certification,omitempty"`

	// Label Human-readable label for the new key.
	Label *string `json:"label,omitempty"`

	// Purpose Purpose of an enrolled key.
	Purpose KeyPurpose `json:"purpose"`

	// SourceInfo Optional context about the requesting system. Producers populate this on a best-effort basis; approvers MUST NOT make security decisions on unauthenticated source metadata.
	SourceInfo *SourceInfo `json:"source_info,omitempty"`
}

// MailboxEnrollResponseApprovedV1 Approved branch of `MailboxEnrollResponsePayloadV1`. Carries the freshly minted public key material so the requester can refer to the new key in subsequent signing / decryption requests.
type MailboxEnrollResponseApprovedV1 struct {
	// Algorithm Key algorithm used.
	Algorithm string `json:"algorithm"`

	// ApprovalProof Canonical Longfellow approval proof carried inside encrypted approval responses.
	ApprovalProof *ApprovalAttestedKeyProof `json:"approval_proof,omitempty"`

	// Attestation Attestation proof that a key was created on attested device hardware.
	Attestation *KeyMetadataAttestation `json:"attestation,omitempty"`

	// DeviceKeyId Device-side key identifier (e.g. iOS Secure Enclave handle) the requester can use to refer to the new key in subsequent requests.
	DeviceKeyId string `json:"device_key_id"`

	// EncryptionFingerprint 40-character hex fingerprint of the ECDH encryption subkey.
	EncryptionFingerprint *string `json:"encryption_fingerprint,omitempty"`

	// EncryptionPublicKeyHex Lowercase hex-encoded ECDH encryption subkey public key (66 hex chars for P-256 33-byte compressed key).
	EncryptionPublicKeyHex *string `json:"encryption_public_key_hex,omitempty"`

	// Fingerprint GPG fingerprint for GPG keys (40 hex chars).
	Fingerprint *string `json:"fingerprint,omitempty"`

	// Id New key identifier. UUID for GPG keys; format defined by the algorithm for other purposes.
	Id string `json:"id"`

	// KeyCreationTimestamp Unix timestamp (seconds) when the key was created.
	KeyCreationTimestamp *int64 `json:"key_creation_timestamp,omitempty"`

	// PublicKeyHex Lowercase hex-encoded public key. 66 hex chars for P-256 33-byte compressed key, or 64 hex chars for Ed25519 32-byte key.
	PublicKeyHex string `json:"public_key_hex"`

	// SshSkFlags Per-credential SSH-SK flags byte the approver baked into a newly enrolled SSH security-key credential. **MUST be present when `purpose` is the SSH signing purpose; absent for all other key purposes.** (The schema cannot express that conditional requirement directly because `MailboxEnrollResponseApprovedV1` is a single monolithic shape with per-type-optional fields like `fingerprint` / `encryption_public_key_hex`; requesters MUST reject SSH-purpose approved responses that omit this field.) The requester MUST persist this byte alongside the credential public key and use it as the request `flags` input on every subsequent `ssh_auth` / `ssh_sign` call. The approver echoes the actual per-signature assertion flags byte back in the success response (see `MailboxSshAuthResponseSuccessV1.flags`); that asserted byte (which MAY differ from this enrollment flags byte when, e.g., the SK could not deliver user verification) is what the requester MUST embed into the OpenSSH SK signature preimage `SHA256(application) || flags || counter || SHA256(data)`. Bit `0x01` is "user presence required" and `0x04` is "user verification required" per the OpenSSH SK protocol.
	SshSkFlags *int `json:"ssh_sk_flags,omitempty"`

	// Status Enrollment outcome discriminator (`approved`).
	Status MailboxEnrollResponseApprovedV1Status `json:"status"`

	// SubkeySignature RFC 4648 standard base64 with `=` padding for the GPG subkey binding signature.
	SubkeySignature *[]byte `json:"subkey_signature,omitempty"`

	// UserIdSignature RFC 4648 standard base64 with `=` padding for the GPG self-certification signature.
	UserIdSignature *[]byte `json:"user_id_signature,omitempty"`
}

// MailboxEnrollResponseApprovedV1Status Enrollment outcome discriminator (`approved`).
type MailboxEnrollResponseApprovedV1Status string

// MailboxEnrollResponsePayloadV1 Response payload for the `enroll` envelope type. Discriminated on `status`: `approved` requires the full key material set; `rejected` requires `error_code`.
type MailboxEnrollResponsePayloadV1 struct {
	union json.RawMessage
}

// MailboxEnrollResponseRejectedV1 Rejected branch of `MailboxEnrollResponsePayloadV1`. Carries the signing error code (and optional human-readable message).
type MailboxEnrollResponseRejectedV1 struct {
	// ErrorCode Numeric error code returned in `*ResponsePayloadV1.error_code` when an approval flow fails. `1=rejected`, `2=timeout`, `3=key_not_found`, `4=invalid_payload`, `5=attestation_failed`, `6=internal_error`.
	ErrorCode SigningErrorCode `json:"error_code"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"error_message,omitempty"`

	// Status Enrollment outcome discriminator (`rejected`).
	Status MailboxEnrollResponseRejectedV1Status `json:"status"`
}

// MailboxEnrollResponseRejectedV1Status Enrollment outcome discriminator (`rejected`).
type MailboxEnrollResponseRejectedV1Status string

// MailboxEnvelopeType Registered set of envelope `type` discriminators. Receivers may decode the envelope successfully but log+drop on unknown values. Adding a new type requires adding it here and shipping the matching payload schema under `payloads/<surface>.yaml`.
type MailboxEnvelopeType string

// MailboxEnvelopeV1 Typed plaintext envelope for NaughtBot mailbox payloads. Receivers dispatch on `type`. The schema is documentary — the auth/mailbox backend never sees the envelope (it is inside HPKE plaintext) and no endpoint accepts it directly. See `core/memories/mailbox-envelope.md` for the canonical decode rules until that memory migrates here with the rest of the schema-relocation follow-up.
type MailboxEnvelopeV1 struct {
	// Id Canonical lower-case RFC 4122 UUID string for idempotency / dedup on the receiver.
	Id openapi_types.UUID `json:"id"`

	// IssuedAt RFC 3339 UTC timestamp with the canonical `Z` suffix. Senders SHOULD emit fractional seconds (`2026-05-03T05:00:00.123Z`); receivers MUST also accept the plain second-precision form (`2026-05-03T05:00:00Z`). Times outside UTC and timestamps lacking the `T` delimiter are rejected.
	IssuedAt string `json:"issued_at"`

	// Payload Type-specific payload, MUST be a JSON object (`{...}`); scalar / array / string roots are not valid envelopes. The internal schema is validated by the per-`type` handler defined under `payloads/`, not by the envelope codec.
	Payload json.RawMessage `json:"payload"`

	// Type Registered type discriminator. Receivers SHOULD validate against the `MailboxEnvelopeType` registry enum at runtime; unknown values MUST be logged and dropped without rejecting the envelope.
	Type string `json:"type"`

	// V Envelope version. Receivers reject unknown versions.
	V MailboxEnvelopeV1V `json:"v"`
}

// MailboxEnvelopeV1V Envelope version. Receivers reject unknown versions.
type MailboxEnvelopeV1V int

// MailboxGpgDecryptRequestPayloadV1 Request payload for the `gpg_decrypt` envelope type. The approver unwraps the OpenPGP Public Key Encrypted Session Key packet using the encryption subkey selected by `device_key_id`.
type MailboxGpgDecryptRequestPayloadV1 struct {
	// ApprovalChallenge Canonical Longfellow / attested-key-zk approval challenge. Producer sends this inside the request payload; the approver binds it into the approval proof returned in the response payload.
	ApprovalChallenge *ApprovalChallenge `json:"approval_challenge,omitempty"`

	// DeviceKeyId Hex-encoded public key selecting which on-device GPG encryption subkey the approver should use for ECDH. The mailbox/poll path requires this because the envelope does not otherwise carry a key identifier.
	DeviceKeyId string `json:"device_key_id"`

	// Display Optional approval-UI metadata. Producers populate this on a best-effort basis; approvers MUST render the wire payload regardless of presence.
	Display *DisplaySchema `json:"display,omitempty"`

	// EncryptedData RFC 4648 standard base64 with `=` padding for the encrypted data to decrypt.
	EncryptedData []byte `json:"encrypted_data"`

	// Pkesk OpenPGP Public Key Encrypted Session Key packet data.
	Pkesk PkeskData `json:"pkesk"`

	// SourceInfo Optional context about the requesting system. Producers populate this on a best-effort basis; approvers MUST NOT make security decisions on unauthenticated source metadata.
	SourceInfo *SourceInfo `json:"source_info,omitempty"`
}

// MailboxGpgDecryptResponseFailureV1 Failure branch of `MailboxGpgDecryptResponsePayloadV1`.
type MailboxGpgDecryptResponseFailureV1 struct {
	// ErrorCode Numeric error code returned in `*ResponsePayloadV1.error_code` when an approval flow fails. `1=rejected`, `2=timeout`, `3=key_not_found`, `4=invalid_payload`, `5=attestation_failed`, `6=internal_error`.
	ErrorCode SigningErrorCode `json:"error_code"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"error_message,omitempty"`
}

// MailboxGpgDecryptResponsePayloadV1 Response payload for the `gpg_decrypt` envelope type. Discriminated as a success / failure pair. The success branch carries both `session_key` and `algorithm`; the failure branch carries `error_code`.
type MailboxGpgDecryptResponsePayloadV1 struct {
	union json.RawMessage
}

// MailboxGpgDecryptResponseSuccessV1 Success branch of `MailboxGpgDecryptResponsePayloadV1`.
type MailboxGpgDecryptResponseSuccessV1 struct {
	// Algorithm OpenPGP symmetric algorithm id (RFC 4880 §9.2).
	Algorithm int32 `json:"algorithm"`

	// ApprovalProof Canonical Longfellow approval proof carried inside encrypted approval responses.
	ApprovalProof *ApprovalAttestedKeyProof `json:"approval_proof,omitempty"`

	// SessionKey RFC 4648 standard base64 with `=` padding for the unwrapped session key.
	SessionKey []byte `json:"session_key"`
}

// MailboxGpgSignRequestPayloadV1 Request payload for the `gpg_sign` envelope type. The approver builds the OpenPGP hash input from `raw_data` and signs the resulting digest with the primary GPG signing key selected by `device_key_id`.
type MailboxGpgSignRequestPayloadV1 struct {
	// ApprovalChallenge Canonical Longfellow / attested-key-zk approval challenge. Producer sends this inside the request payload; the approver binds it into the approval proof returned in the response payload.
	ApprovalChallenge *ApprovalChallenge `json:"approval_challenge,omitempty"`

	// DeviceKeyId Hex-encoded public key selecting which on-device GPG primary key the approver should use for signing. The mailbox/poll path requires this because the envelope does not otherwise carry a key identifier.
	DeviceKeyId string `json:"device_key_id"`

	// Display Optional approval-UI metadata. Producers populate this on a best-effort basis; approvers MUST render the wire payload regardless of presence.
	Display *DisplaySchema `json:"display,omitempty"`

	// RawData RFC 4648 standard base64 with `=` padding for the raw data to sign (preimage). The approver builds the OpenPGP hash input from this preimage and signs the resulting digest.
	RawData []byte `json:"raw_data"`

	// SourceInfo Optional context about the requesting system. Producers populate this on a best-effort basis; approvers MUST NOT make security decisions on unauthenticated source metadata.
	SourceInfo *SourceInfo `json:"source_info,omitempty"`
}

// MailboxGpgSignResponseFailureV1 Failure branch of `MailboxGpgSignResponsePayloadV1`.
type MailboxGpgSignResponseFailureV1 struct {
	// ErrorCode Numeric error code returned in `*ResponsePayloadV1.error_code` when an approval flow fails. `1=rejected`, `2=timeout`, `3=key_not_found`, `4=invalid_payload`, `5=attestation_failed`, `6=internal_error`.
	ErrorCode SigningErrorCode `json:"error_code"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"error_message,omitempty"`
}

// MailboxGpgSignResponsePayloadV1 Response payload for the `gpg_sign` envelope type. Discriminated as a success / failure pair.
type MailboxGpgSignResponsePayloadV1 struct {
	union json.RawMessage
}

// MailboxGpgSignResponseSuccessV1 Success branch of `MailboxGpgSignResponsePayloadV1`.
type MailboxGpgSignResponseSuccessV1 struct {
	// ApprovalProof Canonical Longfellow approval proof carried inside encrypted approval responses.
	ApprovalProof *ApprovalAttestedKeyProof `json:"approval_proof,omitempty"`

	// ArmoredSignature ASCII-armored OpenPGP signature.
	ArmoredSignature string `json:"armored_signature"`
}

// MailboxPkcs11DeriveRequestPayloadV1 Request payload for the `pkcs11_derive` envelope type. The approver runs ECDH between the on-device private key selected by `device_key_id` and the peer public key, optionally feeding the shared secret through a KDF.
type MailboxPkcs11DeriveRequestPayloadV1 struct {
	// ApprovalChallenge Canonical Longfellow / attested-key-zk approval challenge. Producer sends this inside the request payload; the approver binds it into the approval proof returned in the response payload.
	ApprovalChallenge *ApprovalChallenge `json:"approval_challenge,omitempty"`

	// DeviceKeyId Hex-encoded public key selecting which on-device key the approver should use for ECDH.
	DeviceKeyId string `json:"device_key_id"`

	// Display Optional approval-UI metadata. Producers populate this on a best-effort basis; approvers MUST render the wire payload regardless of presence.
	Display *DisplaySchema `json:"display,omitempty"`

	// Kdf Optional key derivation parameters applied to the ECDH shared secret.
	Kdf *Pkcs11DeriveKdfParams `json:"kdf,omitempty"`

	// PeerPublicHex Lowercase hex-encoded peer public key for ECDH (66 hex chars for P-256 33-byte compressed key).
	PeerPublicHex string `json:"peer_public_hex"`

	// SourceInfo Optional context about the requesting system. Producers populate this on a best-effort basis; approvers MUST NOT make security decisions on unauthenticated source metadata.
	SourceInfo *SourceInfo `json:"source_info,omitempty"`
}

// MailboxPkcs11DeriveResponseFailureV1 Failure branch of `MailboxPkcs11DeriveResponsePayloadV1`.
type MailboxPkcs11DeriveResponseFailureV1 struct {
	// ErrorCode Numeric error code returned in `*ResponsePayloadV1.error_code` when an approval flow fails. `1=rejected`, `2=timeout`, `3=key_not_found`, `4=invalid_payload`, `5=attestation_failed`, `6=internal_error`.
	ErrorCode SigningErrorCode `json:"error_code"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"error_message,omitempty"`
}

// MailboxPkcs11DeriveResponsePayloadV1 Response payload for the `pkcs11_derive` envelope type. Discriminated as a success / failure pair.
type MailboxPkcs11DeriveResponsePayloadV1 struct {
	union json.RawMessage
}

// MailboxPkcs11DeriveResponseSuccessV1 Success branch of `MailboxPkcs11DeriveResponsePayloadV1`.
type MailboxPkcs11DeriveResponseSuccessV1 struct {
	// ApprovalProof Canonical Longfellow approval proof carried inside encrypted approval responses.
	ApprovalProof *ApprovalAttestedKeyProof `json:"approval_proof,omitempty"`

	// SharedSecret RFC 4648 standard base64 with `=` padding for the derived shared secret (post-KDF if `kdf` was supplied, otherwise raw ECDH X output).
	SharedSecret []byte `json:"shared_secret"`
}

// MailboxPkcs11SignRequestPayloadV1 Request payload for the `pkcs11_sign` envelope type. The approver computes the SHA-256 digest of `raw_data` and signs it with the on-device key selected by `device_key_id`.
type MailboxPkcs11SignRequestPayloadV1 struct {
	// ApprovalChallenge Canonical Longfellow / attested-key-zk approval challenge. Producer sends this inside the request payload; the approver binds it into the approval proof returned in the response payload.
	ApprovalChallenge *ApprovalChallenge `json:"approval_challenge,omitempty"`

	// DeviceKeyId Hex-encoded public key selecting which on-device key the approver should use for signing.
	DeviceKeyId string `json:"device_key_id"`

	// Display Optional approval-UI metadata. Producers populate this on a best-effort basis; approvers MUST render the wire payload regardless of presence.
	Display *DisplaySchema `json:"display,omitempty"`

	// RawData RFC 4648 standard base64 with `=` padding for the raw data to sign (preimage). The approver computes the SHA-256 digest and signs it.
	RawData []byte `json:"raw_data"`

	// SourceInfo Optional context about the requesting system. Producers populate this on a best-effort basis; approvers MUST NOT make security decisions on unauthenticated source metadata.
	SourceInfo *SourceInfo `json:"source_info,omitempty"`
}

// MailboxPkcs11SignResponseFailureV1 Failure branch of `MailboxPkcs11SignResponsePayloadV1`.
type MailboxPkcs11SignResponseFailureV1 struct {
	// ErrorCode Numeric error code returned in `*ResponsePayloadV1.error_code` when an approval flow fails. `1=rejected`, `2=timeout`, `3=key_not_found`, `4=invalid_payload`, `5=attestation_failed`, `6=internal_error`.
	ErrorCode SigningErrorCode `json:"error_code"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"error_message,omitempty"`
}

// MailboxPkcs11SignResponsePayloadV1 Response payload for the `pkcs11_sign` envelope type. Discriminated as a success / failure pair.
type MailboxPkcs11SignResponsePayloadV1 struct {
	union json.RawMessage
}

// MailboxPkcs11SignResponseSuccessV1 Success branch of `MailboxPkcs11SignResponsePayloadV1`.
type MailboxPkcs11SignResponseSuccessV1 struct {
	// ApprovalProof Canonical Longfellow approval proof carried inside encrypted approval responses.
	ApprovalProof *ApprovalAttestedKeyProof `json:"approval_proof,omitempty"`

	// Signature RFC 4648 standard base64 with `=` padding for the raw signature bytes (no PKCS#1 framing).
	Signature []byte `json:"signature"`
}

// MailboxSshAuthRequestPayloadV1 Request payload for the `ssh_auth` envelope type. The approver signs an SSH user-authentication challenge constructed from `raw_data`, using the on-device key selected by `device_key_id`.
type MailboxSshAuthRequestPayloadV1 struct {
	// Application SSH application identifier (e.g. `ssh:`).
	Application *string `json:"application,omitempty"`

	// ApprovalChallenge Canonical Longfellow / attested-key-zk approval challenge. Producer sends this inside the request payload; the approver binds it into the approval proof returned in the response payload.
	ApprovalChallenge *ApprovalChallenge `json:"approval_challenge,omitempty"`

	// DeviceKeyId Device-side key identifier (e.g. iOS Secure Enclave handle) used to select among enrolled signing keys on the approver.
	DeviceKeyId string `json:"device_key_id"`

	// Display Optional approval-UI metadata. Producers populate this on a best-effort basis; approvers MUST render the wire payload regardless of presence.
	Display *DisplaySchema `json:"display,omitempty"`

	// Flags SSH SK flags bitmask. Default `0x01` requires user presence.
	Flags *int32 `json:"flags,omitempty"`

	// KeyId Identifier of the key to sign with.
	KeyId *string `json:"key_id,omitempty"`

	// RawData RFC 4648 standard base64 with `=` padding for the raw SSH challenge preimage. The approver builds the canonical SSH signature input from this preimage.
	RawData []byte `json:"raw_data"`

	// SourceInfo Optional context about the requesting system. Producers populate this on a best-effort basis; approvers MUST NOT make security decisions on unauthenticated source metadata.
	SourceInfo *SourceInfo `json:"source_info,omitempty"`
}

// MailboxSshAuthResponseFailureV1 Failure branch of `MailboxSshAuthResponsePayloadV1`.
type MailboxSshAuthResponseFailureV1 struct {
	// ErrorCode Numeric error code returned in `*ResponsePayloadV1.error_code` when an approval flow fails. `1=rejected`, `2=timeout`, `3=key_not_found`, `4=invalid_payload`, `5=attestation_failed`, `6=internal_error`.
	ErrorCode SigningErrorCode `json:"error_code"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"error_message,omitempty"`
}

// MailboxSshAuthResponsePayloadV1 Response payload for the `ssh_auth` envelope type. Discriminated as a success / failure pair. Decoders pick `MailboxSshAuthResponseSuccessV1` if `signature` is present and `MailboxSshAuthResponseFailureV1` if `error_code` is present.
type MailboxSshAuthResponsePayloadV1 struct {
	union json.RawMessage
}

// MailboxSshAuthResponseSuccessV1 Success branch of `MailboxSshAuthResponsePayloadV1`. Carries the raw SSH signature plus the per-signature SK assertion flags byte and monotonic counter the signer's secure element returned for this signing operation; all three are required so the requester can rebuild the OpenSSH SK signature preimage (`SHA256(application) || flags || counter || SHA256(data)`) and verify against the enrolled credential public key.
type MailboxSshAuthResponseSuccessV1 struct {
	// ApprovalProof Canonical Longfellow approval proof carried inside encrypted approval responses.
	ApprovalProof *ApprovalAttestedKeyProof `json:"approval_proof,omitempty"`

	// Counter Monotonic counter (u32) the signer's secure element returned for this SK signing operation. Receivers MUST embed this in the OpenSSH SK signature preimage at the position between `flags` and `SHA256(data)` as a 4-byte big-endian unsigned integer. Successive signatures from the same key handle MUST have strictly increasing counter values. The schema declares `format: int64` so 32-bit Go targets can still represent the full u32 range without overflow.
	Counter int64 `json:"counter"`

	// Flags Per-signature SK assertion flags byte the signer's secure element actually asserted with. Approvers MUST either (a) assert with at least the bits the request `flags` byte asked for (UP=0x01, UV=0x04) and return the resulting byte here, or (b) return a `MailboxSshAuthResponseFailureV1` / `MailboxSshSignResponseFailureV1` with the appropriate signing error code. Approvers MUST NOT return a success response whose asserted flags byte clears bits the requester set; that would silently downgrade the security posture (e.g. UV-required → UP-only) below what the request agreed to. Receivers MUST embed this asserted byte at the `flags` position of the OpenSSH SK signature preimage; verification fails if the request `flags` byte is used instead. Receivers SHOULD additionally verify that every bit set in the request `flags` byte is also set here as belt-and-suspenders defence against a misbehaving approver.
	Flags int `json:"flags"`

	// Signature RFC 4648 standard base64 with `=` padding for the raw SSH signature blob (no SSH-wire framing).
	Signature []byte `json:"signature"`
}

// MailboxSshSignRequestPayloadV1 Request payload for the `ssh_sign` envelope type. The approver signs an SSH signature input derived from `raw_data` (e.g. `git commit -S` SSH signing), using the on-device key selected by `device_key_id`.
type MailboxSshSignRequestPayloadV1 struct {
	// Application SSH application identifier (e.g. `ssh:`).
	Application *string `json:"application,omitempty"`

	// ApprovalChallenge Canonical Longfellow / attested-key-zk approval challenge. Producer sends this inside the request payload; the approver binds it into the approval proof returned in the response payload.
	ApprovalChallenge *ApprovalChallenge `json:"approval_challenge,omitempty"`

	// DeviceKeyId Device-side key identifier (e.g. iOS Secure Enclave handle) used to select among enrolled signing keys on the approver.
	DeviceKeyId string `json:"device_key_id"`

	// Display Optional approval-UI metadata. Producers populate this on a best-effort basis; approvers MUST render the wire payload regardless of presence.
	Display *DisplaySchema `json:"display,omitempty"`

	// Flags SSH SK flags bitmask. Default `0x01` requires user presence.
	Flags *int32 `json:"flags,omitempty"`

	// KeyId Identifier of the key to sign with.
	KeyId *string `json:"key_id,omitempty"`

	// RawData RFC 4648 standard base64 with `=` padding for the raw data to sign (preimage). The approver builds the canonical SSH signature input from this preimage.
	RawData []byte `json:"raw_data"`

	// SourceInfo Optional context about the requesting system. Producers populate this on a best-effort basis; approvers MUST NOT make security decisions on unauthenticated source metadata.
	SourceInfo *SourceInfo `json:"source_info,omitempty"`
}

// MailboxSshSignResponseFailureV1 Failure branch of `MailboxSshSignResponsePayloadV1`.
type MailboxSshSignResponseFailureV1 struct {
	// ErrorCode Numeric error code returned in `*ResponsePayloadV1.error_code` when an approval flow fails. `1=rejected`, `2=timeout`, `3=key_not_found`, `4=invalid_payload`, `5=attestation_failed`, `6=internal_error`.
	ErrorCode SigningErrorCode `json:"error_code"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"error_message,omitempty"`
}

// MailboxSshSignResponsePayloadV1 Response payload for the `ssh_sign` envelope type. Discriminated as a success / failure pair.
type MailboxSshSignResponsePayloadV1 struct {
	union json.RawMessage
}

// MailboxSshSignResponseSuccessV1 Success branch of `MailboxSshSignResponsePayloadV1`. Carries the raw SSH signature plus the per-signature SK assertion flags byte and monotonic counter the signer's secure element returned for this signing operation; all three are required so the requester can rebuild the OpenSSH SK signature preimage (`SHA256(application) || flags || counter || SHA256(data)`) and verify against the enrolled credential public key.
type MailboxSshSignResponseSuccessV1 struct {
	// ApprovalProof Canonical Longfellow approval proof carried inside encrypted approval responses.
	ApprovalProof *ApprovalAttestedKeyProof `json:"approval_proof,omitempty"`

	// Counter Monotonic counter (u32) the signer's secure element returned for this SK signing operation. Receivers MUST embed this in the OpenSSH SK signature preimage at the position between `flags` and `SHA256(data)` as a 4-byte big-endian unsigned integer. Successive signatures from the same key handle MUST have strictly increasing counter values. The schema declares `format: int64` so 32-bit Go targets can still represent the full u32 range without overflow.
	Counter int64 `json:"counter"`

	// Flags Per-signature SK assertion flags byte the signer's secure element actually asserted with. Approvers MUST either (a) assert with at least the bits the request `flags` byte asked for (UP=0x01, UV=0x04) and return the resulting byte here, or (b) return a `MailboxSshAuthResponseFailureV1` / `MailboxSshSignResponseFailureV1` with the appropriate signing error code. Approvers MUST NOT return a success response whose asserted flags byte clears bits the requester set; that would silently downgrade the security posture (e.g. UV-required → UP-only) below what the request agreed to. Receivers MUST embed this asserted byte at the `flags` position of the OpenSSH SK signature preimage; verification fails if the request `flags` byte is used instead. Receivers SHOULD additionally verify that every bit set in the request `flags` byte is also set here as belt-and-suspenders defence against a misbehaving approver.
	Flags int `json:"flags"`

	// Signature RFC 4648 standard base64 with `=` padding for the raw SSH signature blob (no SSH-wire framing).
	Signature []byte `json:"signature"`
}

// Pkcs11DeriveKdfParams Optional key derivation parameters applied to the ECDH shared secret.
type Pkcs11DeriveKdfParams struct {
	// Algorithm KDF algorithm name. Approvers MUST reject unknown algorithms.
	Algorithm string `json:"algorithm"`

	// Info RFC 4648 standard base64 with `=` padding for the optional KDF `info` parameter.
	Info *[]byte `json:"info,omitempty"`

	// KeyLength Desired output key length in bytes.
	KeyLength *int32 `json:"key_length,omitempty"`
}

// PkeskData OpenPGP Public Key Encrypted Session Key packet data.
type PkeskData struct {
	// Algorithm OpenPGP public key algorithm (RFC 4880 §9.1). `18` is ECDH.
	Algorithm int32 `json:"algorithm"`

	// EphemeralPoint RFC 4648 standard base64 with `=` padding for the ephemeral ECDH public point (33 bytes compressed).
	EphemeralPoint []byte `json:"ephemeral_point"`

	// KeyId RFC 4648 standard base64 with `=` padding for the 8-byte recipient key id.
	KeyId []byte `json:"key_id"`

	// Version PKESK packet version (typically 3).
	Version int32 `json:"version"`

	// WrappedKey RFC 4648 standard base64 with `=` padding for the AES-wrapped session key.
	WrappedKey []byte `json:"wrapped_key"`
}

// ProcessEntry Entry in a process ancestry chain.
type ProcessEntry struct {
	// Command Command line of the process.
	Command string `json:"command"`

	// Pid Process id.
	Pid int32 `json:"pid"`

	// Username Username running the process.
	Username string `json:"username"`
}

// SigningErrorCode Numeric error code returned in `*ResponsePayloadV1.error_code` when an approval flow fails. `1=rejected`, `2=timeout`, `3=key_not_found`, `4=invalid_payload`, `5=attestation_failed`, `6=internal_error`.
type SigningErrorCode int

// SourceInfo Optional context about the requesting system. Producers populate this on a best-effort basis; approvers MUST NOT make security decisions on unauthenticated source metadata.
type SourceInfo struct {
	// Command Command line of the current process.
	Command *string `json:"command,omitempty"`

	// Hostname Source machine hostname.
	Hostname *string `json:"hostname,omitempty"`

	// LocalIp Local/private IP address.
	LocalIp *string `json:"local_ip,omitempty"`

	// ProcessChain Full process tree from the current process up to init.
	ProcessChain *[]ProcessEntry `json:"process_chain,omitempty"`

	// Username User running the requesting process.
	Username *string `json:"username,omitempty"`
}

// AsMailboxAgeUnwrapResponseSuccessV1 returns the union data inside the MailboxAgeUnwrapResponsePayloadV1 as a MailboxAgeUnwrapResponseSuccessV1
func (t MailboxAgeUnwrapResponsePayloadV1) AsMailboxAgeUnwrapResponseSuccessV1() (MailboxAgeUnwrapResponseSuccessV1, error) {
	var body MailboxAgeUnwrapResponseSuccessV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxAgeUnwrapResponseSuccessV1 overwrites any union data inside the MailboxAgeUnwrapResponsePayloadV1 as the provided MailboxAgeUnwrapResponseSuccessV1
func (t *MailboxAgeUnwrapResponsePayloadV1) FromMailboxAgeUnwrapResponseSuccessV1(v MailboxAgeUnwrapResponseSuccessV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxAgeUnwrapResponseSuccessV1 performs a merge with any union data inside the MailboxAgeUnwrapResponsePayloadV1, using the provided MailboxAgeUnwrapResponseSuccessV1
func (t *MailboxAgeUnwrapResponsePayloadV1) MergeMailboxAgeUnwrapResponseSuccessV1(v MailboxAgeUnwrapResponseSuccessV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMailboxAgeUnwrapResponseFailureV1 returns the union data inside the MailboxAgeUnwrapResponsePayloadV1 as a MailboxAgeUnwrapResponseFailureV1
func (t MailboxAgeUnwrapResponsePayloadV1) AsMailboxAgeUnwrapResponseFailureV1() (MailboxAgeUnwrapResponseFailureV1, error) {
	var body MailboxAgeUnwrapResponseFailureV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxAgeUnwrapResponseFailureV1 overwrites any union data inside the MailboxAgeUnwrapResponsePayloadV1 as the provided MailboxAgeUnwrapResponseFailureV1
func (t *MailboxAgeUnwrapResponsePayloadV1) FromMailboxAgeUnwrapResponseFailureV1(v MailboxAgeUnwrapResponseFailureV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxAgeUnwrapResponseFailureV1 performs a merge with any union data inside the MailboxAgeUnwrapResponsePayloadV1, using the provided MailboxAgeUnwrapResponseFailureV1
func (t *MailboxAgeUnwrapResponsePayloadV1) MergeMailboxAgeUnwrapResponseFailureV1(v MailboxAgeUnwrapResponseFailureV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MailboxAgeUnwrapResponsePayloadV1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MailboxAgeUnwrapResponsePayloadV1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMailboxEnrollResponseApprovedV1 returns the union data inside the MailboxEnrollResponsePayloadV1 as a MailboxEnrollResponseApprovedV1
func (t MailboxEnrollResponsePayloadV1) AsMailboxEnrollResponseApprovedV1() (MailboxEnrollResponseApprovedV1, error) {
	var body MailboxEnrollResponseApprovedV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxEnrollResponseApprovedV1 overwrites any union data inside the MailboxEnrollResponsePayloadV1 as the provided MailboxEnrollResponseApprovedV1
func (t *MailboxEnrollResponsePayloadV1) FromMailboxEnrollResponseApprovedV1(v MailboxEnrollResponseApprovedV1) error {
	v.Status = "approved"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxEnrollResponseApprovedV1 performs a merge with any union data inside the MailboxEnrollResponsePayloadV1, using the provided MailboxEnrollResponseApprovedV1
func (t *MailboxEnrollResponsePayloadV1) MergeMailboxEnrollResponseApprovedV1(v MailboxEnrollResponseApprovedV1) error {
	v.Status = "approved"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMailboxEnrollResponseRejectedV1 returns the union data inside the MailboxEnrollResponsePayloadV1 as a MailboxEnrollResponseRejectedV1
func (t MailboxEnrollResponsePayloadV1) AsMailboxEnrollResponseRejectedV1() (MailboxEnrollResponseRejectedV1, error) {
	var body MailboxEnrollResponseRejectedV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxEnrollResponseRejectedV1 overwrites any union data inside the MailboxEnrollResponsePayloadV1 as the provided MailboxEnrollResponseRejectedV1
func (t *MailboxEnrollResponsePayloadV1) FromMailboxEnrollResponseRejectedV1(v MailboxEnrollResponseRejectedV1) error {
	v.Status = "rejected"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxEnrollResponseRejectedV1 performs a merge with any union data inside the MailboxEnrollResponsePayloadV1, using the provided MailboxEnrollResponseRejectedV1
func (t *MailboxEnrollResponsePayloadV1) MergeMailboxEnrollResponseRejectedV1(v MailboxEnrollResponseRejectedV1) error {
	v.Status = "rejected"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MailboxEnrollResponsePayloadV1) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"status"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t MailboxEnrollResponsePayloadV1) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "approved":
		return t.AsMailboxEnrollResponseApprovedV1()
	case "rejected":
		return t.AsMailboxEnrollResponseRejectedV1()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t MailboxEnrollResponsePayloadV1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MailboxEnrollResponsePayloadV1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMailboxGpgDecryptResponseSuccessV1 returns the union data inside the MailboxGpgDecryptResponsePayloadV1 as a MailboxGpgDecryptResponseSuccessV1
func (t MailboxGpgDecryptResponsePayloadV1) AsMailboxGpgDecryptResponseSuccessV1() (MailboxGpgDecryptResponseSuccessV1, error) {
	var body MailboxGpgDecryptResponseSuccessV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxGpgDecryptResponseSuccessV1 overwrites any union data inside the MailboxGpgDecryptResponsePayloadV1 as the provided MailboxGpgDecryptResponseSuccessV1
func (t *MailboxGpgDecryptResponsePayloadV1) FromMailboxGpgDecryptResponseSuccessV1(v MailboxGpgDecryptResponseSuccessV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxGpgDecryptResponseSuccessV1 performs a merge with any union data inside the MailboxGpgDecryptResponsePayloadV1, using the provided MailboxGpgDecryptResponseSuccessV1
func (t *MailboxGpgDecryptResponsePayloadV1) MergeMailboxGpgDecryptResponseSuccessV1(v MailboxGpgDecryptResponseSuccessV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMailboxGpgDecryptResponseFailureV1 returns the union data inside the MailboxGpgDecryptResponsePayloadV1 as a MailboxGpgDecryptResponseFailureV1
func (t MailboxGpgDecryptResponsePayloadV1) AsMailboxGpgDecryptResponseFailureV1() (MailboxGpgDecryptResponseFailureV1, error) {
	var body MailboxGpgDecryptResponseFailureV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxGpgDecryptResponseFailureV1 overwrites any union data inside the MailboxGpgDecryptResponsePayloadV1 as the provided MailboxGpgDecryptResponseFailureV1
func (t *MailboxGpgDecryptResponsePayloadV1) FromMailboxGpgDecryptResponseFailureV1(v MailboxGpgDecryptResponseFailureV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxGpgDecryptResponseFailureV1 performs a merge with any union data inside the MailboxGpgDecryptResponsePayloadV1, using the provided MailboxGpgDecryptResponseFailureV1
func (t *MailboxGpgDecryptResponsePayloadV1) MergeMailboxGpgDecryptResponseFailureV1(v MailboxGpgDecryptResponseFailureV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MailboxGpgDecryptResponsePayloadV1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MailboxGpgDecryptResponsePayloadV1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMailboxGpgSignResponseSuccessV1 returns the union data inside the MailboxGpgSignResponsePayloadV1 as a MailboxGpgSignResponseSuccessV1
func (t MailboxGpgSignResponsePayloadV1) AsMailboxGpgSignResponseSuccessV1() (MailboxGpgSignResponseSuccessV1, error) {
	var body MailboxGpgSignResponseSuccessV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxGpgSignResponseSuccessV1 overwrites any union data inside the MailboxGpgSignResponsePayloadV1 as the provided MailboxGpgSignResponseSuccessV1
func (t *MailboxGpgSignResponsePayloadV1) FromMailboxGpgSignResponseSuccessV1(v MailboxGpgSignResponseSuccessV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxGpgSignResponseSuccessV1 performs a merge with any union data inside the MailboxGpgSignResponsePayloadV1, using the provided MailboxGpgSignResponseSuccessV1
func (t *MailboxGpgSignResponsePayloadV1) MergeMailboxGpgSignResponseSuccessV1(v MailboxGpgSignResponseSuccessV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMailboxGpgSignResponseFailureV1 returns the union data inside the MailboxGpgSignResponsePayloadV1 as a MailboxGpgSignResponseFailureV1
func (t MailboxGpgSignResponsePayloadV1) AsMailboxGpgSignResponseFailureV1() (MailboxGpgSignResponseFailureV1, error) {
	var body MailboxGpgSignResponseFailureV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxGpgSignResponseFailureV1 overwrites any union data inside the MailboxGpgSignResponsePayloadV1 as the provided MailboxGpgSignResponseFailureV1
func (t *MailboxGpgSignResponsePayloadV1) FromMailboxGpgSignResponseFailureV1(v MailboxGpgSignResponseFailureV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxGpgSignResponseFailureV1 performs a merge with any union data inside the MailboxGpgSignResponsePayloadV1, using the provided MailboxGpgSignResponseFailureV1
func (t *MailboxGpgSignResponsePayloadV1) MergeMailboxGpgSignResponseFailureV1(v MailboxGpgSignResponseFailureV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MailboxGpgSignResponsePayloadV1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MailboxGpgSignResponsePayloadV1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMailboxPkcs11DeriveResponseSuccessV1 returns the union data inside the MailboxPkcs11DeriveResponsePayloadV1 as a MailboxPkcs11DeriveResponseSuccessV1
func (t MailboxPkcs11DeriveResponsePayloadV1) AsMailboxPkcs11DeriveResponseSuccessV1() (MailboxPkcs11DeriveResponseSuccessV1, error) {
	var body MailboxPkcs11DeriveResponseSuccessV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxPkcs11DeriveResponseSuccessV1 overwrites any union data inside the MailboxPkcs11DeriveResponsePayloadV1 as the provided MailboxPkcs11DeriveResponseSuccessV1
func (t *MailboxPkcs11DeriveResponsePayloadV1) FromMailboxPkcs11DeriveResponseSuccessV1(v MailboxPkcs11DeriveResponseSuccessV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxPkcs11DeriveResponseSuccessV1 performs a merge with any union data inside the MailboxPkcs11DeriveResponsePayloadV1, using the provided MailboxPkcs11DeriveResponseSuccessV1
func (t *MailboxPkcs11DeriveResponsePayloadV1) MergeMailboxPkcs11DeriveResponseSuccessV1(v MailboxPkcs11DeriveResponseSuccessV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMailboxPkcs11DeriveResponseFailureV1 returns the union data inside the MailboxPkcs11DeriveResponsePayloadV1 as a MailboxPkcs11DeriveResponseFailureV1
func (t MailboxPkcs11DeriveResponsePayloadV1) AsMailboxPkcs11DeriveResponseFailureV1() (MailboxPkcs11DeriveResponseFailureV1, error) {
	var body MailboxPkcs11DeriveResponseFailureV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxPkcs11DeriveResponseFailureV1 overwrites any union data inside the MailboxPkcs11DeriveResponsePayloadV1 as the provided MailboxPkcs11DeriveResponseFailureV1
func (t *MailboxPkcs11DeriveResponsePayloadV1) FromMailboxPkcs11DeriveResponseFailureV1(v MailboxPkcs11DeriveResponseFailureV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxPkcs11DeriveResponseFailureV1 performs a merge with any union data inside the MailboxPkcs11DeriveResponsePayloadV1, using the provided MailboxPkcs11DeriveResponseFailureV1
func (t *MailboxPkcs11DeriveResponsePayloadV1) MergeMailboxPkcs11DeriveResponseFailureV1(v MailboxPkcs11DeriveResponseFailureV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MailboxPkcs11DeriveResponsePayloadV1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MailboxPkcs11DeriveResponsePayloadV1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMailboxPkcs11SignResponseSuccessV1 returns the union data inside the MailboxPkcs11SignResponsePayloadV1 as a MailboxPkcs11SignResponseSuccessV1
func (t MailboxPkcs11SignResponsePayloadV1) AsMailboxPkcs11SignResponseSuccessV1() (MailboxPkcs11SignResponseSuccessV1, error) {
	var body MailboxPkcs11SignResponseSuccessV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxPkcs11SignResponseSuccessV1 overwrites any union data inside the MailboxPkcs11SignResponsePayloadV1 as the provided MailboxPkcs11SignResponseSuccessV1
func (t *MailboxPkcs11SignResponsePayloadV1) FromMailboxPkcs11SignResponseSuccessV1(v MailboxPkcs11SignResponseSuccessV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxPkcs11SignResponseSuccessV1 performs a merge with any union data inside the MailboxPkcs11SignResponsePayloadV1, using the provided MailboxPkcs11SignResponseSuccessV1
func (t *MailboxPkcs11SignResponsePayloadV1) MergeMailboxPkcs11SignResponseSuccessV1(v MailboxPkcs11SignResponseSuccessV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMailboxPkcs11SignResponseFailureV1 returns the union data inside the MailboxPkcs11SignResponsePayloadV1 as a MailboxPkcs11SignResponseFailureV1
func (t MailboxPkcs11SignResponsePayloadV1) AsMailboxPkcs11SignResponseFailureV1() (MailboxPkcs11SignResponseFailureV1, error) {
	var body MailboxPkcs11SignResponseFailureV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxPkcs11SignResponseFailureV1 overwrites any union data inside the MailboxPkcs11SignResponsePayloadV1 as the provided MailboxPkcs11SignResponseFailureV1
func (t *MailboxPkcs11SignResponsePayloadV1) FromMailboxPkcs11SignResponseFailureV1(v MailboxPkcs11SignResponseFailureV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxPkcs11SignResponseFailureV1 performs a merge with any union data inside the MailboxPkcs11SignResponsePayloadV1, using the provided MailboxPkcs11SignResponseFailureV1
func (t *MailboxPkcs11SignResponsePayloadV1) MergeMailboxPkcs11SignResponseFailureV1(v MailboxPkcs11SignResponseFailureV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MailboxPkcs11SignResponsePayloadV1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MailboxPkcs11SignResponsePayloadV1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMailboxSshAuthResponseSuccessV1 returns the union data inside the MailboxSshAuthResponsePayloadV1 as a MailboxSshAuthResponseSuccessV1
func (t MailboxSshAuthResponsePayloadV1) AsMailboxSshAuthResponseSuccessV1() (MailboxSshAuthResponseSuccessV1, error) {
	var body MailboxSshAuthResponseSuccessV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxSshAuthResponseSuccessV1 overwrites any union data inside the MailboxSshAuthResponsePayloadV1 as the provided MailboxSshAuthResponseSuccessV1
func (t *MailboxSshAuthResponsePayloadV1) FromMailboxSshAuthResponseSuccessV1(v MailboxSshAuthResponseSuccessV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxSshAuthResponseSuccessV1 performs a merge with any union data inside the MailboxSshAuthResponsePayloadV1, using the provided MailboxSshAuthResponseSuccessV1
func (t *MailboxSshAuthResponsePayloadV1) MergeMailboxSshAuthResponseSuccessV1(v MailboxSshAuthResponseSuccessV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMailboxSshAuthResponseFailureV1 returns the union data inside the MailboxSshAuthResponsePayloadV1 as a MailboxSshAuthResponseFailureV1
func (t MailboxSshAuthResponsePayloadV1) AsMailboxSshAuthResponseFailureV1() (MailboxSshAuthResponseFailureV1, error) {
	var body MailboxSshAuthResponseFailureV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxSshAuthResponseFailureV1 overwrites any union data inside the MailboxSshAuthResponsePayloadV1 as the provided MailboxSshAuthResponseFailureV1
func (t *MailboxSshAuthResponsePayloadV1) FromMailboxSshAuthResponseFailureV1(v MailboxSshAuthResponseFailureV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxSshAuthResponseFailureV1 performs a merge with any union data inside the MailboxSshAuthResponsePayloadV1, using the provided MailboxSshAuthResponseFailureV1
func (t *MailboxSshAuthResponsePayloadV1) MergeMailboxSshAuthResponseFailureV1(v MailboxSshAuthResponseFailureV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MailboxSshAuthResponsePayloadV1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MailboxSshAuthResponsePayloadV1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMailboxSshSignResponseSuccessV1 returns the union data inside the MailboxSshSignResponsePayloadV1 as a MailboxSshSignResponseSuccessV1
func (t MailboxSshSignResponsePayloadV1) AsMailboxSshSignResponseSuccessV1() (MailboxSshSignResponseSuccessV1, error) {
	var body MailboxSshSignResponseSuccessV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxSshSignResponseSuccessV1 overwrites any union data inside the MailboxSshSignResponsePayloadV1 as the provided MailboxSshSignResponseSuccessV1
func (t *MailboxSshSignResponsePayloadV1) FromMailboxSshSignResponseSuccessV1(v MailboxSshSignResponseSuccessV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxSshSignResponseSuccessV1 performs a merge with any union data inside the MailboxSshSignResponsePayloadV1, using the provided MailboxSshSignResponseSuccessV1
func (t *MailboxSshSignResponsePayloadV1) MergeMailboxSshSignResponseSuccessV1(v MailboxSshSignResponseSuccessV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMailboxSshSignResponseFailureV1 returns the union data inside the MailboxSshSignResponsePayloadV1 as a MailboxSshSignResponseFailureV1
func (t MailboxSshSignResponsePayloadV1) AsMailboxSshSignResponseFailureV1() (MailboxSshSignResponseFailureV1, error) {
	var body MailboxSshSignResponseFailureV1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMailboxSshSignResponseFailureV1 overwrites any union data inside the MailboxSshSignResponsePayloadV1 as the provided MailboxSshSignResponseFailureV1
func (t *MailboxSshSignResponsePayloadV1) FromMailboxSshSignResponseFailureV1(v MailboxSshSignResponseFailureV1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMailboxSshSignResponseFailureV1 performs a merge with any union data inside the MailboxSshSignResponsePayloadV1, using the provided MailboxSshSignResponseFailureV1
func (t *MailboxSshSignResponsePayloadV1) MergeMailboxSshSignResponseFailureV1(v MailboxSshSignResponseFailureV1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MailboxSshSignResponsePayloadV1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MailboxSshSignResponsePayloadV1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
